# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: /home/linuxbrew/.linuxbrew
        # An explicit key for restoring and saving the cache
        key: linuxbrew-${{ runner.os }}-${{ hashFiles('Formula/*.rb') }}
        # An ordered list of keys to use for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        restore-keys: |
          linuxbrew-${{ runner.os }}-${{ hashFiles('Formula/*.rb') }}
          linuxbrew-${{ runner.os }}-
    
    - name: Homebrew Install Test
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        for recipe in Formula/*.rb
        do
          fname="$(basename "$recipe")"
          brew install "m2700/tap/${fname%.rb}"
        done
